test_util.h: use <cstdint> instead of <stdint.h>
The types used in this file are std:: qualified.
Fixes compile errors with gcc-13:
testing/test_util.cc:8:
testing/test_util.h:35:12: error: ‘uint64_t’ in namespace ‘std’ does not
name a type; did you mean ‘wint_t’?
   35 | const std::uint64_t kOpusCodecDelay = 6500000;

Bug: webm:1808
Change-Id: I7584a9e88cd46677d78bdf28c3e9298a67b74c61